# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: go-getting-started
    ports:
      - 3306:3306
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    command:
      - ./main
      - api
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DBNAME: go-getting-started