name: Docker build

on:
  push:
    branches:
      - master

jobs:
  build-binary:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: update mod
        run: go mod tidy

      - name: build
        run: docker build -t trungduc1104/go-getting-started:latest .
